GET http://localhost:3000/subscribers


###


GET http://localhost:3000/subscribers/62aa0fc83b18183fc4c70f42

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "bee",
    "subscribedToChannel": "bts"
}


###
DELETE http://localhost:3000/subscribers/62aa085d5a7e8cb5fcbcfa9b


###
PATCH http://localhost:3000/subscribers/62aa129841c12939bcde53a5
Content-Type: application/json

{
    "name": "random user"
}